name: Update CS50x Progress

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  # Optional: run nightly
  # schedule:
  #   - cron: "0 0 * * *"  # 00:00 UTC daily

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run updater
        run: |
          python -m pip install --upgrade pip
          python scripts/update_readme.py

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: auto-update CS50x progress table"
            git push
          else
            echo "No changes to commit."
          fi
